version: 1.0.{build}
branches:
  except:
  - master
clone_depth: 1
build_script:
- cmd: C:\Python35-x64\python.exe teapot.py
artifacts:
- path: PKGS\output.zip
  name: TeapotOutput
test: off

